services:
  web:
    build: .
    container_name: portfolio-web
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.areias.it`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
    networks:
      - traefik_web
    expose:
      - "3000"
    # If you prefer to use a prebuilt image, replace build: . with image: your/image

networks:
  traefik_web:
    external: true # must exist (created by your Traefik stack)
