# Production Docker Compose for PortfolioManager
services:
  portfoliomanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfoliomanager
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - NODE_ENV=production
    networks:
      - traefik_web
    labels:
      - traefik.enable=true
      # Main site routing
      - traefik.http.routers.portfoliomanager.rule=Host(`portfolio.areias.it`)
      - traefik.http.routers.portfoliomanager.entrypoints=websecure
      - traefik.http.routers.portfoliomanager.tls.certresolver=le
      - traefik.http.routers.portfoliomanager.middlewares=simple-auth@docker
      - traefik.http.services.portfoliomanager.loadbalancer.server.port=3000
      - traefik.docker.network=traefik_web
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 || res.statusCode === 307 ? 0 : 1); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  traefik_web:
    name: traefik_web
    external: true
